apiVersion: v1
kind: Pod
metadata:
  name: "k8s-msg-api"
  labels:
    name: "lbl-msg-api"
spec:
  containers:
    - 
      image: linoxide/msg-api:v0.0.3
      name:  "msg-api"
      ports:
        - 
          containerPort: 8080 
          name:  "msg-api"